File structure refactor & framing MVP
dasimagin/cart_pole pull request #27
Opened 2022-04-13 16:00 UTC by n0rdstargit

2022-04-16 14:52 UTC, AndBondStyle requested changes

2022-04-16 14:52 UTC, AndBondStyle commented on brain_controller.proto
> +message ResetRequest {
Тут и дальше пошла копипаста. Мы договаривались (второй скрин с доски) что надо сделать 3 отдельных сущности: Config, State и Target + 2 типа сообщения ("reset" и "set T + get S"). Посмотри, как это реализовано в старом proto файле

2022-04-16 14:52 UTC, AndBondStyle commented on brain_controller.proto
> +message ResetRequest {
Тут и дальше пошла копипаста. Мы договаривались (второй скрин с доски) что надо сделать 3 отдельных сущности: Config, State и Target + 2 типа сообщения ("reset" и "set T + get S"). Посмотри, как это реализовано в старом proto файле

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
>  #include <Arduino.h>
Папки src и lib должны быть внутри firmware

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
>  #include <Arduino.h>
Папки src и lib должны быть внутри firmware

2022-04-16 14:52 UTC, AndBondStyle commented on .gitignore
>  **/__pycache__
Почему файл .gitmodules пустой? Там должна быть запинена версия TinyFrame. Сейчас git submodule из-за этого крашится:
```
C:\Users\AndBondStyle\Projects\lab-cartpole-clean>git submodule init
fatal: No url found for submodule path 'lib/TinyFrame' in .gitmodules
```

2022-04-16 14:52 UTC, AndBondStyle commented on .gitignore
>  **/__pycache__
Почему файл .gitmodules пустой? Там должна быть запинена версия TinyFrame. Сейчас git submodule из-за этого крашится:
```
C:\Users\AndBondStyle\Projects\lab-cartpole-clean>git submodule init
fatal: No url found for submodule path 'lib/TinyFrame' in .gitmodules
```

2022-04-16 14:52 UTC, AndBondStyle commented on .gitignore
>  **/__pycache__
Неправильные импорты в файлах:
+ common.util
+ control.trajectory
+ device.tests.test_device
+ `device.tests.functional.__main__`
+ device._device
+ device.wire_interface
+ misc.debug_session_runner
+ sessions.collector
+ `simulator.__init__`

2022-04-16 14:52 UTC, AndBondStyle commented on .gitignore
>  **/__pycache__
Неправильные импорты в файлах:
+ common.util
+ control.trajectory
+ device.tests.test_device
+ device.tests.functional.__main__
+ device._device
+ device.wire_interface
+ misc.debug_session_runner
+ sessions.collector
+ simulator.__init__

2022-04-16 14:52 UTC, AndBondStyle commented on .gitignore
>  **/__pycache__
Для теста можешь позапускать файлы типа `sessions.main` или `device.tests.xxx`. Они много чего импортируют, и должны ломаться если какие импорты указаны неправильно

2022-04-16 14:52 UTC, AndBondStyle commented on .gitignore
>  **/__pycache__
Для теста можешь позапускать файлы типа `sessions.main` или `device.tests.xxx`. Они много чего импортируют, и должны ломаться если какие импорты указаны неправильно

2022-04-16 14:52 UTC, AndBondStyle commented on platformio.ini
> +extra_scripts = post:../build_proto.py
ННС

2022-04-16 14:52 UTC, AndBondStyle commented on platformio.ini
> +extra_scripts = post:../build_proto.py
ННС

2022-04-16 14:52 UTC, AndBondStyle commented on platformio.ini
> +extra_scripts = post:../build_proto.py
Почему post? pre же должно быть

2022-04-16 14:52 UTC, AndBondStyle commented on platformio.ini
> +extra_scripts = post:../build_proto.py
Почему post? pre же должно быть

2022-04-16 14:52 UTC, AndBondStyle commented on scripts/build_proto.py
> +print("KEK" * 20)
чебурек

2022-04-16 14:52 UTC, AndBondStyle commented on scripts/build_proto.py
> +print("KEK" * 20)
чебурек

2022-04-16 14:52 UTC, AndBondStyle commented on src/brain_controller.pb.c
> +
chaotic evil пустые строки

2022-04-16 14:52 UTC, AndBondStyle commented on src/brain_controller.pb.c
> +
chaotic evil пустые строки

2022-04-16 14:52 UTC, AndBondStyle commented on src/brain_controller.pb.c
> +
Если это автогенерируется то забей

2022-04-16 14:52 UTC, AndBondStyle commented on src/brain_controller.pb.c
> +
Если это автогенерируется то забей

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +//#include "utils.h"
?

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +//#include "utils.h"
?

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +#define led 2
Константы пишем в upper case, желательно чтобы имя переменной немного отражало суть (т.е. в данном случае уместнее LED_PIN)

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +#define led 2
Константы пишем в upper case, желательно чтобы имя переменной немного отражало суть (т.е. в данном случае уместнее LED_PIN)

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +#define led 2
+ именем Ильи объявлено, что используем только const переменные, а не дефайны

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +#define led 2
+ именем Ильи объявлено, что используем только const переменные, а не дефайны

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +void processDataGetStateSetTarget();
Немного тяжко это читать, так что предлагаю пока такую штуку: все пока пишем в main.cpp, но разбиваем файл на логические части (можно просто отделять их комментариями в духе "// ==== SECTION XXX ====". Соответственно все константы, типы, функции - разделяем по секциям, к которым они относятся (по смыслу).

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +void processDataGetStateSetTarget();
Немного тяжко это читать, так что предлагаю пока такую штуку: все пока пишем в main.cpp, но разбиваем файл на логические части (можно просто отделять их комментариями в духе "// ==== SECTION XXX ====". Соответственно все константы, типы, функции - разделяем по секциям, к которым они относятся (по смыслу).

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +void encodeGetStateSetTargetResponse(GetStateSetTargetResponse message, uint8_t buffer[]);
Предлагаю придумать простой название для запроса "get state + set target", например "GSTSRequest" или "UpdateRequest" или "ControlRequest".

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +void encodeGetStateSetTargetResponse(GetStateSetTargetResponse message, uint8_t buffer[]);
Предлагаю придумать простой название для запроса "get state + set target", например "GSTSRequest" или "UpdateRequest" или "ControlRequest".

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +    float f = static_cast <float> (rand()) / static_cast <float> (RAND_MAX);
Можно было обойтись числом 42.0f

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +    float f = static_cast <float> (rand()) / static_cast <float> (RAND_MAX);
Можно было обойтись числом 42

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +        digitalWrite(led, HIGH);
Кринж

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +        digitalWrite(led, HIGH);
Кринж

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +    TF_Respond(tf, msg);
Кринж 2

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +    TF_Respond(tf, msg);
Кринж 2

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +    getStateSetTargetResponseMessage.currCartA = 1488;
Вот, нормальные числа пошли

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +    getStateSetTargetResponseMessage.currCartA = 1488;
Вот, нормальные числа пошли

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +{
Ну и классическое chaotic evil форматирование, надо настроить clang-format

2022-04-16 14:52 UTC, AndBondStyle commented on src/main.cpp
> +{
Ну и классическое chaotic evil форматирование, надо настроить clang-format

2022-05-03 18:31 UTC, AndBondStyle requested changes

2022-05-03 18:31 UTC, AndBondStyle commented on .gitignore
> -**/__pycache__
Надо было оставить `**/__pycache__`. А второе упоминание убрать. А ты убрал оба

2022-05-03 18:31 UTC, AndBondStyle commented on cartpole/device/brain_controller_pb2.py
> +# -*- coding: utf-8 -*-
Закоммитился кодген

2022-05-03 18:31 UTC, AndBondStyle commented on cartpole/device/controller_pb2.py
> +import cartpole.device.nanopb_pb2 as nanopb__pb2
И тут тоже кодген? Или это старая версия протокола

2022-05-03 18:31 UTC, AndBondStyle commented on firmware/old_src/encoder.cpp
> -}
Newline

2022-05-03 18:31 UTC, AndBondStyle commented on protocol.proto
> +syntax = "proto3";
Чтобы не потерять: https://developers.google.com/protocol-buffers/docs/style#message_and_field_names

2022-05-03 18:31 UTC, AndBondStyle commented on protocol.proto
> +    float currMotorX = 7; // current motor shaft position (radians)
Позиция и скорость мотора, думаю, не нужна. В итоге ни разу не пользовались этим

2022-05-03 18:31 UTC, AndBondStyle commented on protocol.proto
> +    float currPoleAngle = 4; // current pole angle
Для консистентности, назвал бы `currPoleX`

2022-05-03 18:31 UTC, AndBondStyle commented on protocol.proto
> +    float currCartX = 1; // current cart position float
А куда делись target_cart X, V, A?

2022-05-03 18:31 UTC, AndBondStyle commented on protocol.proto
> +message GSSTResponseRequest {
Надо какое-то более простое слово придумать, типа UpdateRequest, PollRequest, ControlRequest

2022-05-03 18:31 UTC, AndBondStyle commented on protocol.proto
> +    Messagetype type = 1;
Диспатчинг вроде договорились делать на базе tf?

2022-05-05 16:53 UTC, n0rdstargit commented on cartpole/device/brain_controller_pb2.py
> +# -*- coding: utf-8 -*-
Убрал всё, что было помечено как кодген

2023-06-21 18:31 UTC, closed without merging